### ISSUE TITLE
Support for YouTube clips

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#787]
Code in Invidious: https://github.com/SamantazFox/invidious/commit/2512c1bc08c5c26d775c150e7637fa968bb34bb0

I'm not sure how to approach this - extracting the ID in `YoutubeStreamLinkHandlerFactory` itself, or assume that a 36 char getId() is a clip id in YoutubeStreamExtractor.

**Comment by SamantazFox** [comment]
Note: the commit you linked has a minor typo. This one is what I merged: https://github.com/iv-org/invidious/commit/4e44a91d08e45103536235030407c871b3ec5082

**Comment by FireMasterK** [comment]
I've [implemented this in Piped's backend](https://github.com/TeamPiped/Piped-Backend/commit/24482e933e6aafeecc5dd8a454f0df26f402f9fc) directly, due to not being able to find a suitable place in the extractor.

**Comment by attilalearning** [comment]
Happy New Year! :D Is there any update on the youtube clips playing in NewPipe? Version 0.26.1 still shows "no results" for the following url: https://youtube.com/clip/UgkxdWsl8kGYZd7cxUJe0NHnXzBdROVW-B2L

P.S.: NewPipe is AMAZING !!!
